version: '3.8'

services:
  server:
    image: backend-image
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    container_name: backend-dev
